FROM python:3.11.3-slim-bullseye

WORKDIR /usr/src/

COPY ./requirements .
RUN pip install --no-cache-dir -r requirements.txt

COPY ./parsers .

COPY ./scripts .
RUN chmod 0644 cron-jobs
RUN crontab cron-jobs

CMD [ "tail", "-f", "/dev/null"]